### ISSUE TITLE
[feature request] Allow for copy / move Globs

### ISSUE THREAD

**Issue by elgallo** [slick-io/slick#181]
currently copying or moving files with wildcards <code>*</code> or <code>?</code> hangs up the server and will self terminate or require <code>killall node</code> to continue

urgency - low.

**Comment by joshbuddy** [comment]
This change supports wildcard style globs only:
https://github.com/slick-io/slick/pull/188

I think if we want ? or **, we can support those later, but, some of them are a little hard to do efficiently.

**Comment by joshbuddy** [comment]
This supports list and remove globs as well. Should be easy to support the rest of the globbing syntax.

https://github.com/slick-io/slick/pull/197
